server:
   port: 8287
   servlet:
      contextPath: "/node"
      multipart:
         maxFile: 1280MB
         maxRequest: 1280MB
      
klab:
   node:
      submitting: "*"
      searching: "*"
   adapter:
      fscan:
         auth: "*"
      raster:
         auth: "*"
      vector:
         auth: "*"
      wcs:
         auth: "*"
      weather:
         auth: "*"
      wfs:
         auth: "*"
   geoserver:
      password: password
      url: http://geoserver:8080/geoserver 
      user: admin
   postgres:
      host: postgres
      password: password
      port: 5432
      user: postgres
